#ifndef DRIVERCONTROL_GLOBAL_H
#define DRIVERCONTROL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DRIVERCONTROL_LIBRARY)
#  define DRIVERCONTROL_EXPORT Q_DECL_EXPORT
#else
#  define DRIVERCONTROL_EXPORT Q_DECL_IMPORT
#endif

#endif // DRIVERCONTROL_GLOBAL_H
