#ifndef DELIVERYAGENT_GLOBAL_H
#define DELIVERYAGENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DELIVERYAGENT_LIBRARY)
#  define DELIVERYAGENT_EXPORT Q_DECL_EXPORT
#else
#  define DELIVERYAGENT_EXPORT Q_DECL_IMPORT
#endif

#endif // DELIVERYAGENT_GLOBAL_H
